"""Generate HTML reports from OSMOSE simulation results."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from osmose.results import OsmoseResults


def summary_table(results: OsmoseResults) -> pd.DataFrame:
    """Create a summary table with mean/std per species per output type."""
    rows: list[dict] = []
    bio = results.biomass()
    if not bio.empty and "species" in bio.columns:
        for sp, group in bio.groupby("species"):
            rows.append(
                {
                    "species": sp,
                    "biomass_mean": (
                        group["biomass"].mean() if "biomass" in group.columns else None
                    ),
                    "biomass_std": (group["biomass"].std() if "biomass" in group.columns else None),
                }
            )

    yld = results.yield_biomass()
    if not yld.empty and "species" in yld.columns:
        for sp, group in yld.groupby("species"):
            matching = [r for r in rows if r["species"] == sp]
            if matching:
                matching[0]["yield_mean"] = (
                    group["yield"].mean() if "yield" in group.columns else None
                )
            else:
                rows.append(
                    {
                        "species": sp,
                        "yield_mean": (group["yield"].mean() if "yield" in group.columns else None),
                    }
                )

    return pd.DataFrame(rows) if rows else pd.DataFrame()


def generate_report(
    results: OsmoseResults,
    config: dict[str, str],
    output_path: Path,
    fmt: str = "html",
) -> None:
    """Generate a report from OSMOSE results.

    Args:
        results: OsmoseResults instance.
        config: Flat config dict.
        output_path: Where to write the report.
        fmt: "html" (default).
    """
    output_path = Path(output_path)

    # Build summary
    table = summary_table(results)
    table_html = (
        table.to_html(index=False, classes="table") if not table.empty else "<p>No data</p>"
    )

    # Config summary
    nspecies = config.get("simulation.nspecies", "?")
    nyear = config.get("simulation.time.nyear", "?")

    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>OSMOSE Simulation Report</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ color: #1a5276; border-bottom: 3px solid #2980b9; padding-bottom: 10px; }}
        h2 {{ color: #2c3e50; margin-top: 30px; }}
        .table {{ border-collapse: collapse; width: 100%; }}
        .table th, .table td {{ border: 1px solid #ddd; padding: 8px; text-align: right; }}
        .table th {{ background-color: #2980b9; color: white; }}
        .config {{ background: #f8f9fa; padding: 15px; border-radius: 5px; }}
    </style>
</head>
<body>
    <h1>OSMOSE Simulation Report</h1>

    <h2>Configuration</h2>
    <div class="config">
        <p><strong>Species:</strong> {nspecies}</p>
        <p><strong>Simulation years:</strong> {nyear}</p>
    </div>

    <h2>Summary Statistics</h2>
    {table_html}

    <h2>Species Details</h2>
"""
    # Add per-species sections
    bio = results.biomass()
    if not bio.empty and "species" in bio.columns:
        for sp in sorted(bio["species"].unique()):
            sp_data = bio[bio["species"] == sp]
            if "biomass" in sp_data.columns:
                html += f"<h3>{sp}</h3>\n"
                html += f"<p>Mean biomass: {sp_data['biomass'].mean():.1f}</p>\n"

    html += """
    <hr>
    <p><em>Generated by osmose-python</em></p>
</body>
</html>"""

    output_path.write_text(html)
