"""Tests for Java-compatible Xorshift RNG.

Reference values generated by running Java's XSRandom with the same seeds.
"""

import pytest

from osmose.engine.rng_compat import XorshiftRNG


class TestXorshiftNextInt:
    """next_int() must match Java's Random.nextInt(n)."""

    def test_seed42_mod100(self):
        rng = XorshiftRNG(42)
        expected = [50, 26, 14, 15, 88, 97, 13, 59, 15, 81]
        assert [rng.next_int(100) for _ in range(10)] == expected

    def test_seed1_mod100(self):
        rng = XorshiftRNG(1)
        expected = [1, 53, 99, 37, 19]
        assert [rng.next_int(100) for _ in range(5)] == expected

    def test_seed0_all_zeros(self):
        """Seed 0 is a fixed point — all outputs are 0."""
        rng = XorshiftRNG(0)
        assert all(rng.next_int(100) == 0 for _ in range(10))

    def test_power_of_two_bound(self):
        """Power-of-two bounds use the fast path."""
        rng = XorshiftRNG(42)
        vals = [rng.next_int(8) for _ in range(20)]
        assert all(0 <= v < 8 for v in vals)

    def test_bound_1_always_0(self):
        rng = XorshiftRNG(42)
        assert all(rng.next_int(1) == 0 for _ in range(10))

    def test_negative_bound_raises(self):
        rng = XorshiftRNG(42)
        with pytest.raises(ValueError):
            rng.next_int(-1)


class TestXorshiftNextDouble:
    """next_double() must match Java's Random.nextDouble()."""

    def test_seed42_doubles(self):
        rng = XorshiftRNG(42)
        expected = [0.31250968590936634, 0.31499335659101735, 0.95074934178601210]
        for exp in expected:
            got = rng.next_double()
            assert abs(got - exp) < 1e-15, f"{got} != {exp}"

    def test_range_01(self):
        rng = XorshiftRNG(42)
        vals = [rng.next_double() for _ in range(100)]
        assert all(0.0 <= v < 1.0 for v in vals)


class TestXorshiftPermutation:
    """permutation() must match Java's MortalityProcess.shuffleArray."""

    def test_seed42_perm10(self):
        rng = XorshiftRNG(42)
        perm = rng.permutation(10)
        assert list(perm) == [5, 1, 8, 6, 2, 4, 7, 3, 9, 0]

    def test_seed0_perm5(self):
        """Seed 0: all nextInt() return 0, so each element swaps with index 0."""
        rng = XorshiftRNG(0)
        perm = rng.permutation(5)
        assert list(perm) == [1, 2, 3, 4, 0]

    def test_permutation_contains_all(self):
        rng = XorshiftRNG(42)
        perm = rng.permutation(20)
        assert sorted(perm) == list(range(20))


class TestXorshiftShuffle:
    """shuffle() must match permutation() on a list."""

    def test_shuffle_matches_permutation(self):
        rng1 = XorshiftRNG(42)
        perm = rng1.permutation(8)
        rng2 = XorshiftRNG(42)
        arr = list(range(8))
        rng2.shuffle(arr)
        assert arr == list(perm)


class TestXorshiftDeterminism:
    """Same seed must produce identical sequences."""

    def test_same_seed_same_sequence(self):
        rng1 = XorshiftRNG(12345)
        rng2 = XorshiftRNG(12345)
        for _ in range(50):
            assert rng1.next_int(1000) == rng2.next_int(1000)

    def test_different_seed_different_sequence(self):
        rng1 = XorshiftRNG(42)
        rng2 = XorshiftRNG(43)
        vals1 = [rng1.next_int(100) for _ in range(10)]
        vals2 = [rng2.next_int(100) for _ in range(10)]
        assert vals1 != vals2
