"""Bioenergetics OSMOSE parameter definitions."""

from osmose.schema.base import OsmoseField, ParamType

BIOENERGETICS_FIELDS: list[OsmoseField] = [
    # ── Global flags (simulation.bioen.enabled is in simulation.py) ─────────
    OsmoseField(
        key_pattern="simulation.bioen.phit.enabled",
        param_type=ParamType.BOOL,
        default=True,
        description="Apply thermal performance (phi_T) scaling to gross energy",
        category="bioenergetics",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="simulation.bioen.fo2.enabled",
        param_type=ParamType.BOOL,
        default=True,
        description="Apply oxygen limitation (f_O2) scaling to gross energy",
        category="bioenergetics",
        advanced=True,
    ),
    # ── Temperature settings ──────────────────────────────────────────────
    OsmoseField(
        key_pattern="temperature.filename",
        param_type=ParamType.FILE_PATH,
        description="Temperature NetCDF file",
        category="bioenergetics",
    ),
    OsmoseField(
        key_pattern="temperature.varname",
        param_type=ParamType.STRING,
        default="temp",
        description="Temperature variable name in NetCDF file",
        category="bioenergetics",
    ),
    OsmoseField(
        key_pattern="temperature.nsteps.year",
        param_type=ParamType.INT,
        default=12,
        description="Number of temperature time steps per year",
        category="bioenergetics",
    ),
    OsmoseField(
        key_pattern="temperature.factor",
        param_type=ParamType.FLOAT,
        default=1.0,
        description="Multiplicative factor applied to temperature values",
        category="bioenergetics",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="temperature.offset",
        param_type=ParamType.FLOAT,
        default=0.0,
        description="Additive offset applied to temperature values",
        category="bioenergetics",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="temperature.value",
        param_type=ParamType.FLOAT,
        description="Constant temperature value (overrides NetCDF)",
        category="bioenergetics",
        required=False,
    ),
    # ── Oxygen forcing settings ───────────────────────────────────────────
    OsmoseField(
        key_pattern="oxygen.filename",
        param_type=ParamType.FILE_PATH,
        description="Oxygen NetCDF file",
        category="bioenergetics",
        required=False,
    ),
    OsmoseField(
        key_pattern="oxygen.varname",
        param_type=ParamType.STRING,
        default="oxygen",
        description="Oxygen variable name in NetCDF file",
        category="bioenergetics",
    ),
    OsmoseField(
        key_pattern="oxygen.nsteps.year",
        param_type=ParamType.INT,
        default=12,
        description="Number of oxygen time steps per year",
        category="bioenergetics",
    ),
    OsmoseField(
        key_pattern="oxygen.factor",
        param_type=ParamType.FLOAT,
        default=1.0,
        description="Multiplicative factor applied to oxygen values",
        category="bioenergetics",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="oxygen.offset",
        param_type=ParamType.FLOAT,
        default=0.0,
        description="Additive offset applied to oxygen values",
        category="bioenergetics",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="oxygen.value",
        param_type=ParamType.FLOAT,
        description="Constant oxygen value (overrides NetCDF)",
        category="bioenergetics",
        required=False,
    ),
    # ── Per-species bioenergetics parameters ──────────────────────────────
    OsmoseField(
        key_pattern="species.beta.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Allometric scaling exponent for metabolic rate",
        category="bioenergetics",
        indexed=True,
        advanced=True,
    ),
    OsmoseField(
        key_pattern="species.zlayer.sp{idx}",
        param_type=ParamType.INT,
        default=0,
        description="Depth layer index for temperature/oxygen sampling",
        category="bioenergetics",
        indexed=True,
        advanced=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.assimilation.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Assimilation efficiency (fraction of ingested energy absorbed)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.maint.energy.c_m.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Maintenance metabolic coefficient C_m",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.maturity.eta.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Energy density ratio eta (somatic-to-gonad conversion)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.maturity.r.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Reproductive energy allocation fraction r",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.maturity.m0.sp{idx}",
        param_type=ParamType.FLOAT,
        description="LMRN intercept m0: length at maturity = m0 + m1 * age (cm)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.maturity.m1.sp{idx}",
        param_type=ParamType.FLOAT,
        description="LMRN slope m1 for maturity reaction norm",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.mobilized.e.mobi.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Increasing activation energy e_M for Johnson curve (eV)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.mobilized.e.D.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Deactivation energy e_D for Johnson curve (eV)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.mobilized.Tp.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Peak temperature T_P for thermal performance curve (°C)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.maint.e.maint.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Maintenance Arrhenius activation energy (eV)",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.oxygen.c1.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Oxygen dose-response asymptote C1",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.oxygen.c2.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Oxygen half-saturation constant C2",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="predation.ingestion.rate.max.bioen.sp{idx}",
        param_type=ParamType.FLOAT,
        description="Maximum ingestion rate I_max for bioen mode",
        category="bioenergetics",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="predation.coef.ingestion.rate.max.larvae.bioen.sp{idx}",
        param_type=ParamType.FLOAT,
        default=1.0,
        description="Larvae ingestion multiplier theta for bioen mode",
        category="bioenergetics",
        indexed=True,
        advanced=True,
    ),
    OsmoseField(
        key_pattern="predation.c.bioen.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.0,
        description="Larvae ingestion additive correction c_rate for bioen mode",
        category="bioenergetics",
        indexed=True,
        advanced=True,
    ),
    OsmoseField(
        key_pattern="species.bioen.forage.k_for.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.0,
        description="Foraging mortality coefficient k_for",
        category="bioenergetics",
        indexed=True,
        advanced=True,
    ),
]
